'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace DxSample.Web


	Partial Public Class OrdersChart

		''' <summary>
		''' ASPxPanel1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxPanel1 As Global.DevExpress.Web.ASPxPanel
	End Class
End Namespace
